config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                category_film_comments POST   /categories/:category_id/films/:film_id/comments(.:format)                               comments#create
#             new_category_film_comment GET    /categories/:category_id/films/:film_id/comments/new(.:format)                           comments#new
#            edit_category_film_comment GET    /categories/:category_id/films/:film_id/comments/:id/edit(.:format)                      comments#edit
#                 category_film_comment PATCH  /categories/:category_id/films/:film_id/comments/:id(.:format)                           comments#update
#                                       PUT    /categories/:category_id/films/:film_id/comments/:id(.:format)                           comments#update
#                                       DELETE /categories/:category_id/films/:film_id/comments/:id(.:format)                           comments#destroy
#                        category_films GET    /categories/:category_id/films(.:format)                                                 films#index
#                    edit_category_film GET    /categories/:category_id/films/:id/edit(.:format)                                        films#edit
#                         category_film GET    /categories/:category_id/films/:id(.:format)                                             films#show
#                                       PATCH  /categories/:category_id/films/:id(.:format)                                             films#update
#                                       PUT    /categories/:category_id/films/:id(.:format)                                             films#update
#                                       DELETE /categories/:category_id/films/:id(.:format)                                             films#destroy
#                            categories GET    /categories(.:format)                                                                    categories#index
#                                 films POST   /films(.:format)                                                                         films#create
#                              new_film GET    /films/new(.:format)                                                                     films#new
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :categories, only: [:index] do
    resources :films, except: [:new, :create] do
      resources :comments, only: [:create, :destroy, :edit, :new, :update]
    end
  end

  resources :films, only: [:new, :create]



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id          :bigint           not null, primary key
#  deleted_at  :datetime
#  description :text
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Film < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories

  validates_associated :categories
  validates :title, :description, presence: true
  validates_presence_of :categories, :message => "not found"
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @category = Category.find_by(id: params[:category_id]) or not_found
  end

  def show
    @category = Category.find_by(id: params[:category_id])  or not_found
    @film = Film.find_by(id: params[:id]) or not_found
  end

  def new
    @film = Film.new
  end

  def create
    @film = add_categories_to_film(Film.new(film_params))

    if @film.save
      CalculateFilmsNumberJob.perform_now
      redirect_to categories_path, notice: "Film was successfully added."
    else
      render :action => "new"
    end
  end

  def edit
    @category = Category.find_by(id: params[:category_id]) or not_found
    @film = Film.find_by(id: params[:id]) or not_found

    @categories = ""
    @film.categories.each do |category|
      @categories = @categories + category.name + ","
    end
  end

  def update
    category = Category.find_by(id: params[:category_id]) or not_found
    @film = Film.find_by(id: params[:id]) or not_found

    @film = add_categories_to_film(@film)

    if @film.update_attributes(film_params)
      CalculateFilmsNumberJob.perform_now
      redirect_to category_films_path(category), notice: "Film was successfully edited."
    else
      render :action => "edit"
    end
  end

  def destroy
    category = Category.find_by(id: params[:category_id]) or not_found
    film = Film.find_by(id: params[:id]) or not_found

    film.categories.delete(category)

    if film.categories.count == 0
      film.destroy
    end

    CalculateFilmsNumberJob.perform_now

    redirect_to category_films_path(category), notice: "Film was successfully deleted."
  end

  private

  def film_params
    params.require(:film).permit(:title, :description)
  end

  def add_categories_to_film(film)
    categories = params[:categories]
    categories = categories.split(",")

    clear_cat_names = []
    categories.each do |cat|
      clear_cat_names << cat.strip.downcase.capitalize
    end

    cat_objects = Category.where(name: clear_cat_names)
    if cat_objects.length > 0
      cat_objects.each do |cat_object|
        if !film.categories.include?(cat_object)
               film.categories << cat_object
        end
      end
    end

    film
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/create.html.erb
<h1>Add new film</h1>

app/views/films/destroy.html.erb
<h1>Films#destroy</h1>
<p>Find me in app/views/films/destroy.html.erb</p>

app/views/films/edit.html.erb
<h1>Edit film "<%=@film.title %>"</h1>
<%= form_for @film, url: category_film_path(@category, @film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>
      <ul>
        <% @film.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= label_tag :categories, "Categories" %><br />
    <%= text_field_tag :categories, @categories, placeholder: "Names separated by commas" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', category_films_path%>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @category.name %></h1>
<i><%= link_to "Categories", categories_path %> >> <%= @category.name %></i>
<br>
<br>
<table>
  <% @category.films.each do |film| %>
    <tr>
      <td><%= link_to film.title, category_film_path(@category, film) %></td>
      <td><%= link_to 'Edit', edit_category_film_path(@category, film)%></td>
      <td>
        <%= button_to "Delete", category_film_path(@category, film), method: :delete, data: {turbolinks: false, confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>
<br>

app/views/films/new.html.erb
<h1>Add new film</h1>
<%= form_for @film, url: films_path do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>
      <ul>
        <% @film.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= label_tag :categories, "Categories" %><br />
    <%= text_field_tag :categories, nil, placeholder: "Names separated by commas" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', categories_path%>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @film.title %></h1>
<i><%= link_to "Categories", categories_path %> >> <%= link_to @category.name, category_films_path(@category) %> >> <%= @film.title %></i>
<br>
<p><%= @film.description %></p>
<br>
<h3>Comments</h3>
<table>
  <% @film.comments.each do |comment| %>
    <tr>
      <td>
        <b><%= comment.user.name %></b> <i><%= comment.created_at %></i>
        <p><%= comment.comment %></p>
      </td>
      <td><%= link_to 'Edit', edit_category_film_comment_path(@category, @film, comment)%></td>
      <td>
        <%= button_to "Delete", category_film_comment_path(@category, @film, comment), method: :delete, data: {turbolinks: false, confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Add Comment', new_category_film_comment_path(@category, @film) %>

app/views/films/update.html.erb
<h1>Films#update</h1>
<p>Find me in app/views/films/update.html.erb</p>